#!/bin/bash

make

# Run all cities hill_climbing
./output -inst "../DATA/Atlanta.tsp" -alg "hill_climbing" -time 10 -seed 0
# ./output -inst "../DATA/Berlin.tsp" -alg "hill_climbing" -time 10 -seed 0
# ./output -inst "../DATA/Boston.tsp" -alg "hill_climbing" -time 10 -seed 0
# ./output -inst "../DATA/Champaign.tsp" -alg "hill_climbing" -time 10 -seed 0
# ./output -inst "../DATA/Cincinnati.tsp" -alg "hill_climbing" -time 10 -seed 0
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 0
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 0
# ./output -inst "../DATA/Philadelphia.tsp" -alg "hill_climbing" -time 10 -seed 0
# ./output -inst "../DATA/Roanoke.tsp" -alg "hill_climbing" -time 10 -seed 0
# ./output -inst "../DATA/SanFrancisco.tsp" -alg "hill_climbing" -time 10 -seed 0
# ./output -inst "../DATA/Toronto.tsp" -alg "hill_climbing" -time 10 -seed 0
# ./output -inst "../DATA/UKansasState.tsp" -alg "hill_climbing" -time 10 -seed 0
# ./output -inst "../DATA/UMissouri.tsp" -alg "hill_climbing" -time 10 -seed 0


# Run all cities simulated annealing
./output -inst "../DATA/Atlanta.tsp" -alg "simulated_annealing" -time 10 -seed 0
# ./output -inst "../DATA/Berlin.tsp" -alg "simulated_annealing" -time 10 -seed 0
# ./output -inst "../DATA/Boston.tsp" -alg "simulated_annealing" -time 10 -seed 0
# ./output -inst "../DATA/Champaign.tsp" -alg "simulated_annealing" -time 10 -seed 0
# ./output -inst "../DATA/Cincinnati.tsp" -alg "simulated_annealing" -time 10 -seed 0
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 0
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 0
# ./output -inst "../DATA/Philadelphia.tsp" -alg "simulated_annealing" -time 10 -seed 0
# ./output -inst "../DATA/Roanoke.tsp" -alg "simulated_annealing" -time 10 -seed 0
# ./output -inst "../DATA/SanFrancisco.tsp" -alg "simulated_annealing" -time 10 -seed 0
# ./output -inst "../DATA/Toronto.tsp" -alg "simulated_annealing" -time 10 -seed 0
# ./output -inst "../DATA/UKansasState.tsp" -alg "simulated_annealing" -time 10 -seed 0
# ./output -inst "../DATA/UMissouri.tsp" -alg "simulated_annealing" -time 10 -seed 0

# Run Denver 100 times for hill_climbing
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 0
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 1
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 2
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 3
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 4
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 5
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 6
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 7
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 8
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 9
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 10
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 11
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 12
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 13
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 14
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 15
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 16
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 17
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 18
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 19
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 20
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 21
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 22
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 23
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 24
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 25
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 26
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 27
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 28
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 29
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 30
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 31
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 32
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 33
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 34
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 35
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 36
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 37
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 38
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 39
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 40
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 41
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 42
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 43
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 44
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 45
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 46
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 47
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 48
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 49
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 50
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 51
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 52
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 53
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 54
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 55
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 56
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 57
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 58
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 59
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 60
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 61
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 62
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 63
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 64
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 65
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 66
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 67
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 68
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 69
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 70
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 71
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 72
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 73
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 74
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 75
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 76
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 77
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 78
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 79
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 80
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 81
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 82
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 83
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 84
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 85
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 86
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 87
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 88
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 89
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 90
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 91
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 92
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 93
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 94
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 95
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 96
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 97
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 98
# ./output -inst "../DATA/Denver.tsp" -alg "hill_climbing" -time 10 -seed 99

# # Run Denver 100 times for annealing
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 0
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 1
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 2
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 3
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 4
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 5
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 6
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 7
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 8
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 9
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 10
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 11
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 12
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 13
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 14
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 15
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 16
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 17
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 18
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 19
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 20
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 21
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 22
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 23
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 24
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 25
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 26
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 27
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 28
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 29
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 30
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 31
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 32
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 33
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 34
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 35
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 36
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 37
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 38
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 39
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 40
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 41
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 42
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 43
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 44
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 45
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 46
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 47
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 48
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 49
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 50
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 51
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 52
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 53
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 54
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 55
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 56
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 57
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 58
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 59
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 60
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 61
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 62
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 63
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 64
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 65
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 66
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 67
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 68
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 69
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 70
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 71
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 72
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 73
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 74
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 75
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 76
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 77
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 78
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 79
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 80
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 81
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 82
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 83
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 84
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 85
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 86
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 87
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 88
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 89
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 90
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 91
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 92
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 93
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 94
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 95
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 96
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 97
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 98
# ./output -inst "../DATA/Denver.tsp" -alg "simulated_annealing" -time 10 -seed 99

# # Run NYC 100 times for hill_climbing
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 0
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 1
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 2
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 3
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 4
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 5
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 6
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 7
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 8
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 9
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 10
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 11
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 12
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 13
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 14
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 15
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 16
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 17
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 18
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 19
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 20
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 21
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 22
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 23
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 24
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 25
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 26
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 27
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 28
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 29
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 30
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 31
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 32
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 33
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 34
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 35
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 36
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 37
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 38
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 39
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 40
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 41
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 42
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 43
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 44
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 45
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 46
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 47
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 48
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 49
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 50
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 51
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 52
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 53
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 54
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 55
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 56
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 57
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 58
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 59
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 60
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 61
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 62
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 63
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 64
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 65
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 66
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 67
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 68
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 69
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 70
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 71
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 72
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 73
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 74
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 75
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 76
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 77
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 78
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 79
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 80
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 81
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 82
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 83
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 84
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 85
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 86
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 87
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 88
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 89
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 90
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 91
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 92
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 93
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 94
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 95
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 96
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 97
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 98
# ./output -inst "../DATA/NYC.tsp" -alg "hill_climbing" -time 10 -seed 99

# # Run NYC 100 times for annealing
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 0
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 1
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 2
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 3
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 4
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 5
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 6
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 7
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 8
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 9
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 10
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 11
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 12
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 13
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 14
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 15
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 16
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 17
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 18
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 19
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 20
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 21
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 22
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 23
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 24
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 25
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 26
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 27
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 28
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 29
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 30
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 31
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 32
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 33
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 34
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 35
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 36
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 37
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 38
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 39
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 40
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 41
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 42
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 43
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 44
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 45
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 46
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 47
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 48
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 49
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 50
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 51
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 52
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 53
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 54
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 55
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 56
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 57
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 58
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 59
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 60
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 61
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 62
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 63
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 64
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 65
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 66
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 67
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 68
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 69
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 70
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 71
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 72
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 73
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 74
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 75
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 76
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 77
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 78
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 79
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 80
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 81
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 82
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 83
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 84
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 85
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 86
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 87
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 88
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 89
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 90
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 91
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 92
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 93
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 94
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 95
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 96
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 97
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 98
# ./output -inst "../DATA/NYC.tsp" -alg "simulated_annealing" -time 10 -seed 99